import { StyleSheet } from "react-native";
import type { UseThemeReturn } from "@/constants/theme/hooks/useTheme";

export const makeStyles = ({
  colors,
  fonts,
  fontSizes,
  spacing,
  radii,
  layout,
  iconSizes,
}: UseThemeReturn) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.bgPrimary,
    },
    scrollContent: {
      paddingHorizontal: layout.screenPaddingH,
      paddingTop: layout.screenPaddingV,
      paddingBottom: layout.tabBarHeight + layout.screenPaddingV,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: spacing.lg,
    },
    profileChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.sm,
      flexShrink: 1,
    },
    avatarImage: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.bgSecondary,
    },
    avatarFallback: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.bgSecondary,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.borderDefault,
    },
    avatarInitials: {
      fontFamily: fonts.mono,
      fontSize: fontSizes.body,
      color: colors.primary,
    },
    username: {
      fontFamily: fonts.display,
      fontSize: fontSizes.h2,
      color: colors.primary,
      textTransform: "uppercase",
      letterSpacing: 2,
    },
    subLabel: {
      fontFamily: fonts.caption,
      fontSize: fontSizes.caption,
      color: colors.textMuted,
    },
    baseCard: {
      backgroundColor: colors.bgSecondary,
      borderRadius: radii.md,
      borderWidth: 1,
      borderColor: colors.borderDefault,
      borderLeftWidth: 3,
      borderLeftColor: colors.primary,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      marginBottom: spacing.xs,
    },
    baseCardTag: {
      fontFamily: fonts.mono,
      fontSize: fontSizes.micro,
      color: colors.primaryLight,
      letterSpacing: 2,
      marginBottom: 2,
    },
    baseCardName: {
      fontFamily: fonts.display,
      fontSize: fontSizes.h1,
      color: colors.textPrimary,
      textTransform: "uppercase",
      letterSpacing: 1.5,
    },
    baseCardCoordRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.xs,
      marginTop: spacing.xs,
    },
    baseCardCoords: {
      fontFamily: fonts.mono,
      fontSize: fontSizes.micro,
      color: colors.textMuted,
      letterSpacing: 0.5,
    },
    levelChip: {
      backgroundColor: colors.bgSecondary,
      borderRadius: radii.md,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xs,
      alignItems: "center",
      marginLeft: spacing.sm,
    },
    levelLabel: {
      fontFamily: fonts.mono,
      fontSize: fontSizes.micro,
      color: colors.textMuted,
      textTransform: "uppercase",
      letterSpacing: 1,
    },
    levelValue: {
      fontFamily: fonts.mono,
      fontSize: fontSizes.dataLg,
      color: colors.primary,
      lineHeight: fontSizes.dataLg * 1.1,
    },
    metricsRow: {
      flexDirection: "row",
      gap: layout.cardGap,
      marginBottom: spacing.xl,
    },
    criticalPanel: {
      backgroundColor: colors.dangerBg,
      borderRadius: radii.lg,
      borderWidth: 1,
      borderColor: colors.borderDanger,
      padding: spacing.md,
      marginBottom: spacing.lg,
    },
    categoryLabel: {
      fontFamily: fonts.heading,
      fontSize: fontSizes.caption,
      color: colors.textMuted,
      textTransform: "uppercase",
      letterSpacing: 1.5,
      marginBottom: spacing.xs,
    },
    categoryDot: {
      color: colors.danger,
    },
    categoryGroup: {
      marginBottom: spacing.md,
    },
    emptyText: {
      fontFamily: fonts.caption,
      fontSize: fontSizes.body,
      color: colors.textMuted,
      marginBottom: spacing.xl,
    },
    viewAllRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: spacing.xs,
      paddingVertical: spacing.md,
    },
    viewAllText: {
      fontFamily: fonts.heading,
      fontSize: fontSizes.body,
      color: colors.primary,
    },
    errorContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: layout.screenPaddingH,
      gap: spacing.lg,
    },
    errorTitle: {
      fontFamily: fonts.heading,
      fontSize: fontSizes.h3,
      color: colors.textDanger,
      textAlign: "center",
    },
    errorSubtitle: {
      fontFamily: fonts.caption,
      fontSize: fontSizes.caption,
      color: colors.textMuted,
      textAlign: "center",
    },
    retryButton: {
      backgroundColor: colors.primary,
      paddingHorizontal: spacing.xl,
      paddingVertical: spacing.md,
      borderRadius: radii.md,
    },
    retryText: {
      fontFamily: fonts.heading,
      fontSize: fontSizes.body,
      color: colors.textInverse,
    },
  });
